version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: kx_store
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  springapp:
    image: openjdk:17
    container_name: spring-container
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
